# Copyright (C) 2017-2018 Betalo AB - All Rights Reserved

---
notifications:
  email: false

language: go

go:
  - 1.10.x

install:
  - make deps

script:
  - make copyright
  - make install lint
  - make build
  - make test
